config/routes.rb
Rails.application.routes.draw do
  get '/' => 'homes#top'
  resources :books
  root to: "books#top"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end

    if @book.save
      flash[:notice] = 'successfully'
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update

    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render :edit
    end

    if @book.update(book_params)
        flash[:notice] = 'successfully'
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
    if book.destroy
      flash[:notice] = 'successfully'
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>

<h4><strong>Title:</strong></h4>
<%= f.text_field :title %>

<h4><strong>Body:</strong></h4>
<%= f.text_area :body %>

<%= f.submit 'Update Book' %>

<% end %>

<p><%= link_to "show", book_path(@book.id) %></p>
|
<p><%= link_to "back", books_path %></p>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
    <tr>
    <th>Title</th>
    <th>Body</th>
    </tr>
    <% @books.each do |book| %>
    <tr>
        <th><%= book.title %></th>
        <th><%= book.body %></th>
        <th><%= link_to "Show", book_path(book.id) %></th>
        <th><%= link_to "Edit", edit_book_path(book.id) %></th>
        <th><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></th>
    </tr>
    <% end %>
</table>

<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @book, local: true) do |f| %>
    <h3>Title</h3>
    <%= f.text_field :title %>
    <h3>Body</h3>
    <%= f.text_area :body %>
    <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<body>
    <p>
        <strong>Title:</strong>
        <%= @book.title %>
    </p>

    <p>
        <strong>Body:</strong>
        <%= @book.body %>
    </p>

    <p><%= link_to "edit", edit_book_path(@book.id) %></p>
    |
    <p><%= link_to "back", books_path %></p>
</body>

app/views/homes/top.html.erb
  <html>
  <head>
    <title>bookers</title>
  </head>

<body>
<h1>
  ようこそ
  <strong>Bookers</strong>
   へ !
</h1>
<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p>
  <%= link_to "start", books_path %>
</p>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>